/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackerIndexRouteImport } from './routes/tracker/index'
import { Route as TrackerNewRouteImport } from './routes/tracker/new'
import { Route as TrackerBackupRouteImport } from './routes/tracker/backup'
import { Route as TrackerSheetIdRouteImport } from './routes/tracker/$sheetId'
import { Route as DemoTrpcTodoRouteImport } from './routes/demo/trpc-todo'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTanchatRouteImport } from './routes/demo/tanchat'
import { Route as DemoStructuredRouteImport } from './routes/demo/structured'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoImageRouteImport } from './routes/demo/image'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example.guitars/index'
import { Route as TrackerSheetIdSummaryRouteImport } from './routes/tracker/$sheetId.summary'
import { Route as TrackerSheetIdMarkRouteImport } from './routes/tracker/$sheetId.mark'
import { Route as TrackerSheetIdEditRouteImport } from './routes/tracker/$sheetId.edit'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example.guitars/$guitarId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTtsRouteImport } from './routes/demo/api.tts'
import { Route as DemoApiTranscriptionRouteImport } from './routes/demo/api.transcription'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiTanchatRouteImport } from './routes/demo/api.tanchat'
import { Route as DemoApiStructuredRouteImport } from './routes/demo/api.structured'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiImageRouteImport } from './routes/demo/api.image'
import { Route as DemoApiAvailableProvidersRouteImport } from './routes/demo/api.available-providers'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerIndexRoute = TrackerIndexRouteImport.update({
  id: '/tracker/',
  path: '/tracker/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerNewRoute = TrackerNewRouteImport.update({
  id: '/tracker/new',
  path: '/tracker/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerBackupRoute = TrackerBackupRouteImport.update({
  id: '/tracker/backup',
  path: '/tracker/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerSheetIdRoute = TrackerSheetIdRouteImport.update({
  id: '/tracker/$sheetId',
  path: '/tracker/$sheetId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTrpcTodoRoute = DemoTrpcTodoRouteImport.update({
  id: '/demo/trpc-todo',
  path: '/demo/trpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanchatRoute = DemoTanchatRouteImport.update({
  id: '/demo/tanchat',
  path: '/demo/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStructuredRoute = DemoStructuredRouteImport.update({
  id: '/demo/structured',
  path: '/demo/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoImageRoute = DemoImageRouteImport.update({
  id: '/demo/image',
  path: '/demo/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerSheetIdSummaryRoute = TrackerSheetIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => TrackerSheetIdRoute,
} as any)
const TrackerSheetIdMarkRoute = TrackerSheetIdMarkRouteImport.update({
  id: '/mark',
  path: '/mark',
  getParentRoute: () => TrackerSheetIdRoute,
} as any)
const TrackerSheetIdEditRoute = TrackerSheetIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TrackerSheetIdRoute,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTtsRoute = DemoApiTtsRouteImport.update({
  id: '/demo/api/tts',
  path: '/demo/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTranscriptionRoute = DemoApiTranscriptionRouteImport.update({
  id: '/demo/api/transcription',
  path: '/demo/api/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTanchatRoute = DemoApiTanchatRouteImport.update({
  id: '/demo/api/tanchat',
  path: '/demo/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiStructuredRoute = DemoApiStructuredRouteImport.update({
  id: '/demo/api/structured',
  path: '/demo/api/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiImageRoute = DemoApiImageRouteImport.update({
  id: '/demo/api/image',
  path: '/demo/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAvailableProvidersRoute =
  DemoApiAvailableProvidersRouteImport.update({
    id: '/demo/api/available-providers',
    path: '/demo/api/available-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/image': typeof DemoImageRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/structured': typeof DemoStructuredRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/tracker/$sheetId': typeof TrackerSheetIdRouteWithChildren
  '/tracker/backup': typeof TrackerBackupRoute
  '/tracker/new': typeof TrackerNewRoute
  '/tracker': typeof TrackerIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/image': typeof DemoApiImageRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/structured': typeof DemoApiStructuredRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/api/transcription': typeof DemoApiTranscriptionRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/tracker/$sheetId/edit': typeof TrackerSheetIdEditRoute
  '/tracker/$sheetId/mark': typeof TrackerSheetIdMarkRoute
  '/tracker/$sheetId/summary': typeof TrackerSheetIdSummaryRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/image': typeof DemoImageRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/structured': typeof DemoStructuredRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/tracker/$sheetId': typeof TrackerSheetIdRouteWithChildren
  '/tracker/backup': typeof TrackerBackupRoute
  '/tracker/new': typeof TrackerNewRoute
  '/tracker': typeof TrackerIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/image': typeof DemoApiImageRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/structured': typeof DemoApiStructuredRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/api/transcription': typeof DemoApiTranscriptionRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/tracker/$sheetId/edit': typeof TrackerSheetIdEditRoute
  '/tracker/$sheetId/mark': typeof TrackerSheetIdMarkRoute
  '/tracker/$sheetId/summary': typeof TrackerSheetIdSummaryRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/image': typeof DemoImageRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/structured': typeof DemoStructuredRoute
  '/demo/tanchat': typeof DemoTanchatRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/tracker/$sheetId': typeof TrackerSheetIdRouteWithChildren
  '/tracker/backup': typeof TrackerBackupRoute
  '/tracker/new': typeof TrackerNewRoute
  '/tracker/': typeof TrackerIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/image': typeof DemoApiImageRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/structured': typeof DemoApiStructuredRoute
  '/demo/api/tanchat': typeof DemoApiTanchatRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/api/transcription': typeof DemoApiTranscriptionRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/tracker/$sheetId/edit': typeof TrackerSheetIdEditRoute
  '/tracker/$sheetId/mark': typeof TrackerSheetIdMarkRoute
  '/tracker/$sheetId/summary': typeof TrackerSheetIdSummaryRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/image'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/structured'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/tracker/$sheetId'
    | '/tracker/backup'
    | '/tracker/new'
    | '/tracker'
    | '/api/trpc/$'
    | '/demo/api/available-providers'
    | '/demo/api/image'
    | '/demo/api/names'
    | '/demo/api/structured'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/api/transcription'
    | '/demo/api/tts'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/tracker/$sheetId/edit'
    | '/tracker/$sheetId/mark'
    | '/tracker/$sheetId/summary'
    | '/example/guitars'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/image'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/structured'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/tracker/$sheetId'
    | '/tracker/backup'
    | '/tracker/new'
    | '/tracker'
    | '/api/trpc/$'
    | '/demo/api/available-providers'
    | '/demo/api/image'
    | '/demo/api/names'
    | '/demo/api/structured'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/api/transcription'
    | '/demo/api/tts'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/tracker/$sheetId/edit'
    | '/tracker/$sheetId/mark'
    | '/tracker/$sheetId/summary'
    | '/example/guitars'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/demo/image'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/structured'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/tracker/$sheetId'
    | '/tracker/backup'
    | '/tracker/new'
    | '/tracker/'
    | '/api/trpc/$'
    | '/demo/api/available-providers'
    | '/demo/api/image'
    | '/demo/api/names'
    | '/demo/api/structured'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/api/transcription'
    | '/demo/api/tts'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/tracker/$sheetId/edit'
    | '/tracker/$sheetId/mark'
    | '/tracker/$sheetId/summary'
    | '/example/guitars/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoImageRoute: typeof DemoImageRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoStructuredRoute: typeof DemoStructuredRoute
  DemoTanchatRoute: typeof DemoTanchatRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTrpcTodoRoute: typeof DemoTrpcTodoRoute
  TrackerSheetIdRoute: typeof TrackerSheetIdRouteWithChildren
  TrackerBackupRoute: typeof TrackerBackupRoute
  TrackerNewRoute: typeof TrackerNewRoute
  TrackerIndexRoute: typeof TrackerIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  DemoApiAvailableProvidersRoute: typeof DemoApiAvailableProvidersRoute
  DemoApiImageRoute: typeof DemoApiImageRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiStructuredRoute: typeof DemoApiStructuredRoute
  DemoApiTanchatRoute: typeof DemoApiTanchatRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoApiTranscriptionRoute: typeof DemoApiTranscriptionRoute
  DemoApiTtsRoute: typeof DemoApiTtsRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/': {
      id: '/tracker/'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/new': {
      id: '/tracker/new'
      path: '/tracker/new'
      fullPath: '/tracker/new'
      preLoaderRoute: typeof TrackerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/backup': {
      id: '/tracker/backup'
      path: '/tracker/backup'
      fullPath: '/tracker/backup'
      preLoaderRoute: typeof TrackerBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/$sheetId': {
      id: '/tracker/$sheetId'
      path: '/tracker/$sheetId'
      fullPath: '/tracker/$sheetId'
      preLoaderRoute: typeof TrackerSheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/trpc-todo': {
      id: '/demo/trpc-todo'
      path: '/demo/trpc-todo'
      fullPath: '/demo/trpc-todo'
      preLoaderRoute: typeof DemoTrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanchat': {
      id: '/demo/tanchat'
      path: '/demo/tanchat'
      fullPath: '/demo/tanchat'
      preLoaderRoute: typeof DemoTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/structured': {
      id: '/demo/structured'
      path: '/demo/structured'
      fullPath: '/demo/structured'
      preLoaderRoute: typeof DemoStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/image': {
      id: '/demo/image'
      path: '/demo/image'
      fullPath: '/demo/image'
      preLoaderRoute: typeof DemoImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/$sheetId/summary': {
      id: '/tracker/$sheetId/summary'
      path: '/summary'
      fullPath: '/tracker/$sheetId/summary'
      preLoaderRoute: typeof TrackerSheetIdSummaryRouteImport
      parentRoute: typeof TrackerSheetIdRoute
    }
    '/tracker/$sheetId/mark': {
      id: '/tracker/$sheetId/mark'
      path: '/mark'
      fullPath: '/tracker/$sheetId/mark'
      preLoaderRoute: typeof TrackerSheetIdMarkRouteImport
      parentRoute: typeof TrackerSheetIdRoute
    }
    '/tracker/$sheetId/edit': {
      id: '/tracker/$sheetId/edit'
      path: '/edit'
      fullPath: '/tracker/$sheetId/edit'
      preLoaderRoute: typeof TrackerSheetIdEditRouteImport
      parentRoute: typeof TrackerSheetIdRoute
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tts': {
      id: '/demo/api/tts'
      path: '/demo/api/tts'
      fullPath: '/demo/api/tts'
      preLoaderRoute: typeof DemoApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/transcription': {
      id: '/demo/api/transcription'
      path: '/demo/api/transcription'
      fullPath: '/demo/api/transcription'
      preLoaderRoute: typeof DemoApiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tanchat': {
      id: '/demo/api/tanchat'
      path: '/demo/api/tanchat'
      fullPath: '/demo/api/tanchat'
      preLoaderRoute: typeof DemoApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/structured': {
      id: '/demo/api/structured'
      path: '/demo/api/structured'
      fullPath: '/demo/api/structured'
      preLoaderRoute: typeof DemoApiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/image': {
      id: '/demo/api/image'
      path: '/demo/api/image'
      fullPath: '/demo/api/image'
      preLoaderRoute: typeof DemoApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/available-providers': {
      id: '/demo/api/available-providers'
      path: '/demo/api/available-providers'
      fullPath: '/demo/api/available-providers'
      preLoaderRoute: typeof DemoApiAvailableProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrackerSheetIdRouteChildren {
  TrackerSheetIdEditRoute: typeof TrackerSheetIdEditRoute
  TrackerSheetIdMarkRoute: typeof TrackerSheetIdMarkRoute
  TrackerSheetIdSummaryRoute: typeof TrackerSheetIdSummaryRoute
}

const TrackerSheetIdRouteChildren: TrackerSheetIdRouteChildren = {
  TrackerSheetIdEditRoute: TrackerSheetIdEditRoute,
  TrackerSheetIdMarkRoute: TrackerSheetIdMarkRoute,
  TrackerSheetIdSummaryRoute: TrackerSheetIdSummaryRoute,
}

const TrackerSheetIdRouteWithChildren = TrackerSheetIdRoute._addFileChildren(
  TrackerSheetIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoImageRoute: DemoImageRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoStructuredRoute: DemoStructuredRoute,
  DemoTanchatRoute: DemoTanchatRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTrpcTodoRoute: DemoTrpcTodoRoute,
  TrackerSheetIdRoute: TrackerSheetIdRouteWithChildren,
  TrackerBackupRoute: TrackerBackupRoute,
  TrackerNewRoute: TrackerNewRoute,
  TrackerIndexRoute: TrackerIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  DemoApiAvailableProvidersRoute: DemoApiAvailableProvidersRoute,
  DemoApiImageRoute: DemoApiImageRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiStructuredRoute: DemoApiStructuredRoute,
  DemoApiTanchatRoute: DemoApiTanchatRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoApiTranscriptionRoute: DemoApiTranscriptionRoute,
  DemoApiTtsRoute: DemoApiTtsRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
